language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-django16
    - python: 2.7
      env: TOXENV=py27-django17
    - python: 2.7
      env: TOXENV=py27-django18
    - python: 3.3
      env: TOXENV=py33-django16
    - python: 3.3
      env: TOXENV=py33-django17
    - python: 3.3
      env: TOXENV=py33-django18
    - python: 3.4
      env: TOXENV=py34-django16
    - python: 3.4
      env: TOXENV=py34-django17
    - python: 3.4
      env: TOXENV=py34-django18
    - python: 3.5
      env: TOXENV=py35-django18
    - python: 3.5
      env: TOXENV=py35-django19
    - python: pypy
      env: TOXENV=pypy-django16
    - python: pypy
      env: TOXENV=pypy-django17
    - python: pypy
      env: TOXENV=pypy-django18
    - python: pypy
      env: TOXENV=pypy-django19
    - python: pypy3
      env: TOXENV=pypy3-django16
    - python: pypy3
      env: TOXENV=pypy3-django17
    - python: pypy3
      env: TOXENV=pypy3-django18
    - python: pypy3
      env: TOXENV=pypy3-django19
install:
  - pip install tox
  - pip install codecov
script:
  - tox
after_success:
  - bash <(curl -s https://codecov.io/bash)
